[build]
  command = "npm run build:generate"
  publish = "dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:generate"
  
[context.deploy-preview]
  command = "npm run build:generate"
  
[context.branch-deploy]
  command = "npm run build:generate"
