[build]
  command = "npm run build:generate"
  publish = "dist"
  base = "."
  environment = { SECRETS_SCAN_OMIT_PATHS = "dist/**,openapi_inspect.json,src/generated/**,package-lock.json" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm run build:generate"
  environment = { SECRETS_SCAN_OMIT_PATHS = "dist/**,openapi_inspect.json,src/generated/**,package-lock.json" }
  
[context.deploy-preview]
  command = "npm run build:generate"
  environment = { SECRETS_SCAN_OMIT_PATHS = "dist/**,openapi_inspect.json,src/generated/**,package-lock.json" }
  
[context.branch-deploy]
  command = "npm run build:generate"
  environment = { SECRETS_SCAN_OMIT_PATHS = "dist/**,openapi_inspect.json,src/generated/**,package-lock.json" }
